# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Lappy/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-7300-MSI/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/SHA256v2/SHA256v2.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/SHA256v2/SHA256v2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/SHA256v2/SHA256v2.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/AND2x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/AND2x1_32.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/AND3x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/AND4x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/Add32.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/BinaryComp_6.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/BitReg_32.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/DEMUX2x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/DEMUX48x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/DEMUX4x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/DEMUX8x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/DFF_POS.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/FF_reg.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/FullAdd.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/LoopControl.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/LoopCounter.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/LoopIndex.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/MUX2x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/MUX2x1_32.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/MUX48x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/MUX48x1_32.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/MUX4x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/MUX64x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/MUX64x1_32.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/MUX8x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/MainCirc1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/MainCirc2.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/NOT1x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/NOT1x1_32.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/OR2x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/OR3x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/OR4x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/RRo11.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/RRo13.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/RRo17.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/RRo18.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/RRo19.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/RRo2.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/RRo22.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/RRo25.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/RRo6.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/RRo7.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/RSh10.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/RSh3.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/SHA256_control.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/SHA256_data.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/State_m0.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/XNOR2x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/XOR2x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/XOR2x1_32.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/XOR3x1.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/XOR3x1_32.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/atoh_reg.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/ch.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/h_reg.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/k_reg.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/maj.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/w_reg.vhd}
  {C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/SHA256.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Lappy/Desktop/DuyTran_Capstone/Version 2/Nexys4DDR_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top SHA256 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SHA256.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SHA256_utilization_synth.rpt -pb SHA256_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
